language = "C"
include_guard = "M68000_FFI_H"

include_version = false
sys_includes = ["stdint.h"]
includes = ["m68000.h"]
no_includes = true
cpp_compat = true

braces = "NextLine"
line_length = 120
tab_width = 4
documentation = true
documentation_style = "auto"
line_endings = "CRLF" # also "CR", "CRLF", "Native"
style = "both"

usize_is_size_t = true

[fn]
args = "horizontal"
sort_by = "None"

[const]
allow_constexpr = true
